### ISSUE TITLE
500 error when opening http://127.0.0.1:5000/

### ISSUE THREAD

**Issue by khanakia** [zuzke/capNcook#2]
```sh
 capNcook git:(master) ✗ python3 app.py
cat: /var/lib/tor/capNcook/hostname: No such file or directory
hidden service ->
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.10.118:5000
Press CTRL+C to quit
[2023-12-29 20:59:29,218] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/stem/socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khanakia/Downloads/capNcook/app.py", line 84, in index
    entry_node, exit_node = get_last_entry_exit_relay()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khanakia/Downloads/capNcook/app.py", line 30, in get_last_entry_exit_relay
    with Controller.from_port(port=9051) as controller:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/stem/control.py", line 1033, in from_port
    control_port = stem.socket.ControlPort(address, port)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/stem/socket.py", line 503, in __init__
    self.connect()
  File "/opt/homebrew/lib/python3.11/site-packages/stem/socket.py", line 172, in connect
    self._socket = self._make_socket()
                   ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/stem/socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 61] Connection refused
127.0.0.1 - - [29/Dec/2023 20:59:29] "GET / HTTP/1.1" 500 -
```

**Comment by khanakia** [comment]
It worked when i changed the port to 9050 but then according to this image 
https://my.visme.co/view/n0qey8xz-voql9kxgqo162x1w what is the the use 9051 port ?
```
with Controller.from_port(port=9051) as controller:
```
to
```
with Controller.from_port(port=9050) as controller:
```

**Comment by hoodietramp** [comment]
tor network traffic routes through port 9050 making requests using socks5 proxy, but tor control port 9051 is seperate port used to grab the entry and exit nodes while making a tor connection, this port is usually used to integrate other tools to monitor tor or in automated scripts for working with tor circuits or just tor daemon service.

**Comment by khanakia** [comment]
Ok, so how do i make the script work with 9051 port then? If I use 9051 then it gives the above error

**Comment by hoodietramp** [comment]
change tor control port in /etc/tor/torrc from 9051 to maybe like 9052 and sudo systemctl restart tor and kindly check linkedin for futhur communication (:
